// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: addition.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Augend      int64                  `protobuf:"varint,1,opt,name=augend"`
	xxx_hidden_Addend      int64                  `protobuf:"varint,2,opt,name=addend"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_addition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddRequest) GetAugend() int64 {
	if x != nil {
		return x.xxx_hidden_Augend
	}
	return 0
}

func (x *AddRequest) GetAddend() int64 {
	if x != nil {
		return x.xxx_hidden_Addend
	}
	return 0
}

func (x *AddRequest) SetAugend(v int64) {
	x.xxx_hidden_Augend = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AddRequest) SetAddend(v int64) {
	x.xxx_hidden_Addend = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AddRequest) HasAugend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddRequest) HasAddend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddRequest) ClearAugend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Augend = 0
}

func (x *AddRequest) ClearAddend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Addend = 0
}

type AddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The number that the addend is added to.
	Augend *int64
	// The number to be added to the augend.
	Addend *int64
}

func (b0 AddRequest_builder) Build() *AddRequest {
	m0 := &AddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Augend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Augend = *b.Augend
	}
	if b.Addend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Addend = *b.Addend
	}
	return m0
}

type AddResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sum         int64                  `protobuf:"varint,1,opt,name=sum"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_addition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddResponse) GetSum() int64 {
	if x != nil {
		return x.xxx_hidden_Sum
	}
	return 0
}

func (x *AddResponse) SetSum(v int64) {
	x.xxx_hidden_Sum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AddResponse) HasSum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddResponse) ClearSum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Sum = 0
}

type AddResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The sum of the augend and addend.
	Sum *int64
}

func (b0 AddResponse_builder) Build() *AddResponse {
	m0 := &AddResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Sum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Sum = *b.Sum
	}
	return m0
}

var File_addition_proto protoreflect.FileDescriptor

const file_addition_proto_rawDesc = "" +
	"\n" +
	"\x0eaddition.proto\x12\x16monax.example.addition\x1a!google/protobuf/go_features.proto\"<\n" +
	"\n" +
	"AddRequest\x12\x16\n" +
	"\x06augend\x18\x01 \x01(\x03R\x06augend\x12\x16\n" +
	"\x06addend\x18\x02 \x01(\x03R\x06addend\"\x1f\n" +
	"\vAddResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x03R\x03sum2Z\n" +
	"\bAddition\x12N\n" +
	"\x03Add\x12\".monax.example.addition.AddRequest\x1a#.monax.example.addition.AddResponseB?Z5github.com/openconfig/monax/example/math/addition/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe9\a"

var file_addition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_addition_proto_goTypes = []any{
	(*AddRequest)(nil),  // 0: monax.example.addition.AddRequest
	(*AddResponse)(nil), // 1: monax.example.addition.AddResponse
}
var file_addition_proto_depIdxs = []int32{
	0, // 0: monax.example.addition.Addition.Add:input_type -> monax.example.addition.AddRequest
	1, // 1: monax.example.addition.Addition.Add:output_type -> monax.example.addition.AddResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_addition_proto_init() }
func file_addition_proto_init() {
	if File_addition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addition_proto_rawDesc), len(file_addition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_addition_proto_goTypes,
		DependencyIndexes: file_addition_proto_depIdxs,
		MessageInfos:      file_addition_proto_msgTypes,
	}.Build()
	File_addition_proto = out.File
	file_addition_proto_goTypes = nil
	file_addition_proto_depIdxs = nil
}
