// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: division.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Division_Divide_FullMethodName = "/monax.example.division.Division/Divide"
)

// DivisionClient is the client API for Division service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DivisionClient interface {
	// Receives two terms and replies with the quotient.
	Divide(ctx context.Context, in *DivideRequest, opts ...grpc.CallOption) (*DivideResponse, error)
}

type divisionClient struct {
	cc grpc.ClientConnInterface
}

func NewDivisionClient(cc grpc.ClientConnInterface) DivisionClient {
	return &divisionClient{cc}
}

func (c *divisionClient) Divide(ctx context.Context, in *DivideRequest, opts ...grpc.CallOption) (*DivideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DivideResponse)
	err := c.cc.Invoke(ctx, Division_Divide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DivisionServer is the server API for Division service.
// All implementations must embed UnimplementedDivisionServer
// for forward compatibility.
type DivisionServer interface {
	// Receives two terms and replies with the quotient.
	Divide(context.Context, *DivideRequest) (*DivideResponse, error)
	mustEmbedUnimplementedDivisionServer()
}

// UnimplementedDivisionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDivisionServer struct{}

func (UnimplementedDivisionServer) Divide(context.Context, *DivideRequest) (*DivideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Divide not implemented")
}
func (UnimplementedDivisionServer) mustEmbedUnimplementedDivisionServer() {}
func (UnimplementedDivisionServer) testEmbeddedByValue()                  {}

// UnsafeDivisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DivisionServer will
// result in compilation errors.
type UnsafeDivisionServer interface {
	mustEmbedUnimplementedDivisionServer()
}

func RegisterDivisionServer(s grpc.ServiceRegistrar, srv DivisionServer) {
	// If the following call panics, it indicates UnimplementedDivisionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Division_ServiceDesc, srv)
}

func _Division_Divide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DivideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DivisionServer).Divide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Division_Divide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DivisionServer).Divide(ctx, req.(*DivideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Division_ServiceDesc is the grpc.ServiceDesc for Division service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Division_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monax.example.division.Division",
	HandlerType: (*DivisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Divide",
			Handler:    _Division_Divide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "division.proto",
}
