// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: division.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DivideRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Dividend    int64                  `protobuf:"varint,1,opt,name=dividend"`
	xxx_hidden_Divisor     int64                  `protobuf:"varint,2,opt,name=divisor"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DivideRequest) Reset() {
	*x = DivideRequest{}
	mi := &file_division_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivideRequest) ProtoMessage() {}

func (x *DivideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_division_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DivideRequest) GetDividend() int64 {
	if x != nil {
		return x.xxx_hidden_Dividend
	}
	return 0
}

func (x *DivideRequest) GetDivisor() int64 {
	if x != nil {
		return x.xxx_hidden_Divisor
	}
	return 0
}

func (x *DivideRequest) SetDividend(v int64) {
	x.xxx_hidden_Dividend = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DivideRequest) SetDivisor(v int64) {
	x.xxx_hidden_Divisor = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DivideRequest) HasDividend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DivideRequest) HasDivisor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DivideRequest) ClearDividend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Dividend = 0
}

func (x *DivideRequest) ClearDivisor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Divisor = 0
}

type DivideRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The number that is divided by the divisor.
	Dividend *int64
	// The number that divides the dividend.
	Divisor *int64
}

func (b0 DivideRequest_builder) Build() *DivideRequest {
	m0 := &DivideRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Dividend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Dividend = *b.Dividend
	}
	if b.Divisor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Divisor = *b.Divisor
	}
	return m0
}

type DivideResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Quotient    int64                  `protobuf:"varint,1,opt,name=quotient"`
	xxx_hidden_Remainder   int64                  `protobuf:"varint,2,opt,name=remainder"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DivideResponse) Reset() {
	*x = DivideResponse{}
	mi := &file_division_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivideResponse) ProtoMessage() {}

func (x *DivideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_division_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DivideResponse) GetQuotient() int64 {
	if x != nil {
		return x.xxx_hidden_Quotient
	}
	return 0
}

func (x *DivideResponse) GetRemainder() int64 {
	if x != nil {
		return x.xxx_hidden_Remainder
	}
	return 0
}

func (x *DivideResponse) SetQuotient(v int64) {
	x.xxx_hidden_Quotient = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DivideResponse) SetRemainder(v int64) {
	x.xxx_hidden_Remainder = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DivideResponse) HasQuotient() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DivideResponse) HasRemainder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DivideResponse) ClearQuotient() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Quotient = 0
}

func (x *DivideResponse) ClearRemainder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Remainder = 0
}

type DivideResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The whole number result of dividing the dividend by the divisor.
	Quotient *int64
	// The remainder of the division.
	Remainder *int64
}

func (b0 DivideResponse_builder) Build() *DivideResponse {
	m0 := &DivideResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Quotient != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Quotient = *b.Quotient
	}
	if b.Remainder != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Remainder = *b.Remainder
	}
	return m0
}

var File_division_proto protoreflect.FileDescriptor

const file_division_proto_rawDesc = "" +
	"\n" +
	"\x0edivision.proto\x12\x16monax.example.division\x1a!google/protobuf/go_features.proto\"E\n" +
	"\rDivideRequest\x12\x1a\n" +
	"\bdividend\x18\x01 \x01(\x03R\bdividend\x12\x18\n" +
	"\adivisor\x18\x02 \x01(\x03R\adivisor\"J\n" +
	"\x0eDivideResponse\x12\x1a\n" +
	"\bquotient\x18\x01 \x01(\x03R\bquotient\x12\x1c\n" +
	"\tremainder\x18\x02 \x01(\x03R\tremainder2c\n" +
	"\bDivision\x12W\n" +
	"\x06Divide\x12%.monax.example.division.DivideRequest\x1a&.monax.example.division.DivideResponseB?Z5github.com/openconfig/monax/example/math/division/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_division_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_division_proto_goTypes = []any{
	(*DivideRequest)(nil),  // 0: monax.example.division.DivideRequest
	(*DivideResponse)(nil), // 1: monax.example.division.DivideResponse
}
var file_division_proto_depIdxs = []int32{
	0, // 0: monax.example.division.Division.Divide:input_type -> monax.example.division.DivideRequest
	1, // 1: monax.example.division.Division.Divide:output_type -> monax.example.division.DivideResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_division_proto_init() }
func file_division_proto_init() {
	if File_division_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_division_proto_rawDesc), len(file_division_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_division_proto_goTypes,
		DependencyIndexes: file_division_proto_depIdxs,
		MessageInfos:      file_division_proto_msgTypes,
	}.Build()
	File_division_proto = out.File
	file_division_proto_goTypes = nil
	file_division_proto_depIdxs = nil
}
