// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: subtraction.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubtractRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Minuend     int64                  `protobuf:"varint,1,opt,name=minuend"`
	xxx_hidden_Subtrahend  int64                  `protobuf:"varint,2,opt,name=subtrahend"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubtractRequest) Reset() {
	*x = SubtractRequest{}
	mi := &file_subtraction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractRequest) ProtoMessage() {}

func (x *SubtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtraction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubtractRequest) GetMinuend() int64 {
	if x != nil {
		return x.xxx_hidden_Minuend
	}
	return 0
}

func (x *SubtractRequest) GetSubtrahend() int64 {
	if x != nil {
		return x.xxx_hidden_Subtrahend
	}
	return 0
}

func (x *SubtractRequest) SetMinuend(v int64) {
	x.xxx_hidden_Minuend = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SubtractRequest) SetSubtrahend(v int64) {
	x.xxx_hidden_Subtrahend = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SubtractRequest) HasMinuend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SubtractRequest) HasSubtrahend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SubtractRequest) ClearMinuend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Minuend = 0
}

func (x *SubtractRequest) ClearSubtrahend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Subtrahend = 0
}

type SubtractRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The number that the subtrahend subtracts from.
	Minuend *int64
	// The number that is subtracted from the minuend.
	Subtrahend *int64
}

func (b0 SubtractRequest_builder) Build() *SubtractRequest {
	m0 := &SubtractRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Minuend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Minuend = *b.Minuend
	}
	if b.Subtrahend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Subtrahend = *b.Subtrahend
	}
	return m0
}

type SubtractResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Difference  int64                  `protobuf:"varint,1,opt,name=difference"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SubtractResponse) Reset() {
	*x = SubtractResponse{}
	mi := &file_subtraction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractResponse) ProtoMessage() {}

func (x *SubtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtraction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubtractResponse) GetDifference() int64 {
	if x != nil {
		return x.xxx_hidden_Difference
	}
	return 0
}

func (x *SubtractResponse) SetDifference(v int64) {
	x.xxx_hidden_Difference = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SubtractResponse) HasDifference() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SubtractResponse) ClearDifference() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Difference = 0
}

type SubtractResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The difference of the minuend and the subtrahend.
	Difference *int64
}

func (b0 SubtractResponse_builder) Build() *SubtractResponse {
	m0 := &SubtractResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Difference != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Difference = *b.Difference
	}
	return m0
}

var File_subtraction_proto protoreflect.FileDescriptor

const file_subtraction_proto_rawDesc = "" +
	"\n" +
	"\x11subtraction.proto\x12\x19monax.example.subtraction\x1a!google/protobuf/go_features.proto\"K\n" +
	"\x0fSubtractRequest\x12\x18\n" +
	"\aminuend\x18\x01 \x01(\x03R\aminuend\x12\x1e\n" +
	"\n" +
	"subtrahend\x18\x02 \x01(\x03R\n" +
	"subtrahend\"2\n" +
	"\x10SubtractResponse\x12\x1e\n" +
	"\n" +
	"difference\x18\x01 \x01(\x03R\n" +
	"difference2r\n" +
	"\vSubtraction\x12c\n" +
	"\bSubtract\x12*.monax.example.subtraction.SubtractRequest\x1a+.monax.example.subtraction.SubtractResponseBBZ8github.com/openconfig/monax/example/math/subtraction/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_subtraction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subtraction_proto_goTypes = []any{
	(*SubtractRequest)(nil),  // 0: monax.example.subtraction.SubtractRequest
	(*SubtractResponse)(nil), // 1: monax.example.subtraction.SubtractResponse
}
var file_subtraction_proto_depIdxs = []int32{
	0, // 0: monax.example.subtraction.Subtraction.Subtract:input_type -> monax.example.subtraction.SubtractRequest
	1, // 1: monax.example.subtraction.Subtraction.Subtract:output_type -> monax.example.subtraction.SubtractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subtraction_proto_init() }
func file_subtraction_proto_init() {
	if File_subtraction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subtraction_proto_rawDesc), len(file_subtraction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subtraction_proto_goTypes,
		DependencyIndexes: file_subtraction_proto_depIdxs,
		MessageInfos:      file_subtraction_proto_msgTypes,
	}.Build()
	File_subtraction_proto = out.File
	file_subtraction_proto_goTypes = nil
	file_subtraction_proto_depIdxs = nil
}
