// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: subtraction.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subtraction_Subtract_FullMethodName = "/monax.example.subtraction.Subtraction/Subtract"
)

// SubtractionClient is the client API for Subtraction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubtractionClient interface {
	// Receives two terms and replies with the difference.
	Subtract(ctx context.Context, in *SubtractRequest, opts ...grpc.CallOption) (*SubtractResponse, error)
}

type subtractionClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtractionClient(cc grpc.ClientConnInterface) SubtractionClient {
	return &subtractionClient{cc}
}

func (c *subtractionClient) Subtract(ctx context.Context, in *SubtractRequest, opts ...grpc.CallOption) (*SubtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubtractResponse)
	err := c.cc.Invoke(ctx, Subtraction_Subtract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtractionServer is the server API for Subtraction service.
// All implementations must embed UnimplementedSubtractionServer
// for forward compatibility.
type SubtractionServer interface {
	// Receives two terms and replies with the difference.
	Subtract(context.Context, *SubtractRequest) (*SubtractResponse, error)
	mustEmbedUnimplementedSubtractionServer()
}

// UnimplementedSubtractionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubtractionServer struct{}

func (UnimplementedSubtractionServer) Subtract(context.Context, *SubtractRequest) (*SubtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subtract not implemented")
}
func (UnimplementedSubtractionServer) mustEmbedUnimplementedSubtractionServer() {}
func (UnimplementedSubtractionServer) testEmbeddedByValue()                     {}

// UnsafeSubtractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubtractionServer will
// result in compilation errors.
type UnsafeSubtractionServer interface {
	mustEmbedUnimplementedSubtractionServer()
}

func RegisterSubtractionServer(s grpc.ServiceRegistrar, srv SubtractionServer) {
	// If the following call panics, it indicates UnimplementedSubtractionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subtraction_ServiceDesc, srv)
}

func _Subtraction_Subtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtractionServer).Subtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subtraction_Subtract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtractionServer).Subtract(ctx, req.(*SubtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subtraction_ServiceDesc is the grpc.ServiceDesc for Subtraction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subtraction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monax.example.subtraction.Subtraction",
	HandlerType: (*SubtractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subtract",
			Handler:    _Subtraction_Subtract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subtraction.proto",
}
