// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: multiplication.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiplyRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Multiplier   int64                  `protobuf:"varint,1,opt,name=multiplier"`
	xxx_hidden_Multiplicand int64                  `protobuf:"varint,2,opt,name=multiplicand"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MultiplyRequest) Reset() {
	*x = MultiplyRequest{}
	mi := &file_multiplication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyRequest) ProtoMessage() {}

func (x *MultiplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiplication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MultiplyRequest) GetMultiplier() int64 {
	if x != nil {
		return x.xxx_hidden_Multiplier
	}
	return 0
}

func (x *MultiplyRequest) GetMultiplicand() int64 {
	if x != nil {
		return x.xxx_hidden_Multiplicand
	}
	return 0
}

func (x *MultiplyRequest) SetMultiplier(v int64) {
	x.xxx_hidden_Multiplier = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *MultiplyRequest) SetMultiplicand(v int64) {
	x.xxx_hidden_Multiplicand = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *MultiplyRequest) HasMultiplier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MultiplyRequest) HasMultiplicand() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MultiplyRequest) ClearMultiplier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Multiplier = 0
}

func (x *MultiplyRequest) ClearMultiplicand() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Multiplicand = 0
}

type MultiplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The number that is multiplied into the multiplicand.
	Multiplier *int64
	// The number that is multiplied by the multiplier.
	Multiplicand *int64
}

func (b0 MultiplyRequest_builder) Build() *MultiplyRequest {
	m0 := &MultiplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Multiplier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Multiplier = *b.Multiplier
	}
	if b.Multiplicand != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Multiplicand = *b.Multiplicand
	}
	return m0
}

type MultiplyResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Product     int64                  `protobuf:"varint,1,opt,name=product"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MultiplyResponse) Reset() {
	*x = MultiplyResponse{}
	mi := &file_multiplication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplyResponse) ProtoMessage() {}

func (x *MultiplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiplication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MultiplyResponse) GetProduct() int64 {
	if x != nil {
		return x.xxx_hidden_Product
	}
	return 0
}

func (x *MultiplyResponse) SetProduct(v int64) {
	x.xxx_hidden_Product = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *MultiplyResponse) HasProduct() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MultiplyResponse) ClearProduct() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Product = 0
}

type MultiplyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The product of the multiplier and the multiplicand.
	Product *int64
}

func (b0 MultiplyResponse_builder) Build() *MultiplyResponse {
	m0 := &MultiplyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Product != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Product = *b.Product
	}
	return m0
}

var File_multiplication_proto protoreflect.FileDescriptor

const file_multiplication_proto_rawDesc = "" +
	"\n" +
	"\x14multiplication.proto\x12\x1cmonax.example.multiplication\x1a!google/protobuf/go_features.proto\"U\n" +
	"\x0fMultiplyRequest\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x01 \x01(\x03R\n" +
	"multiplier\x12\"\n" +
	"\fmultiplicand\x18\x02 \x01(\x03R\fmultiplicand\",\n" +
	"\x10MultiplyResponse\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\x03R\aproduct2{\n" +
	"\x0eMultiplication\x12i\n" +
	"\bMultiply\x12-.monax.example.multiplication.MultiplyRequest\x1a..monax.example.multiplication.MultiplyResponseBEZ;github.com/openconfig/monax/example/math/multiplication/api\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_multiplication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiplication_proto_goTypes = []any{
	(*MultiplyRequest)(nil),  // 0: monax.example.multiplication.MultiplyRequest
	(*MultiplyResponse)(nil), // 1: monax.example.multiplication.MultiplyResponse
}
var file_multiplication_proto_depIdxs = []int32{
	0, // 0: monax.example.multiplication.Multiplication.Multiply:input_type -> monax.example.multiplication.MultiplyRequest
	1, // 1: monax.example.multiplication.Multiplication.Multiply:output_type -> monax.example.multiplication.MultiplyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiplication_proto_init() }
func file_multiplication_proto_init() {
	if File_multiplication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiplication_proto_rawDesc), len(file_multiplication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiplication_proto_goTypes,
		DependencyIndexes: file_multiplication_proto_depIdxs,
		MessageInfos:      file_multiplication_proto_msgTypes,
	}.Build()
	File_multiplication_proto = out.File
	file_multiplication_proto_goTypes = nil
	file_multiplication_proto_depIdxs = nil
}
