// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0
// source: multiplication.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Multiplication_Multiply_FullMethodName = "/monax.example.multiplication.Multiplication/Multiply"
)

// MultiplicationClient is the client API for Multiplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplicationClient interface {
	// Receives two terms and replies with the product.
	Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
}

type multiplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplicationClient(cc grpc.ClientConnInterface) MultiplicationClient {
	return &multiplicationClient{cc}
}

func (c *multiplicationClient) Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, Multiplication_Multiply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplicationServer is the server API for Multiplication service.
// All implementations must embed UnimplementedMultiplicationServer
// for forward compatibility.
type MultiplicationServer interface {
	// Receives two terms and replies with the product.
	Multiply(context.Context, *MultiplyRequest) (*MultiplyResponse, error)
	mustEmbedUnimplementedMultiplicationServer()
}

// UnimplementedMultiplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiplicationServer struct{}

func (UnimplementedMultiplicationServer) Multiply(context.Context, *MultiplyRequest) (*MultiplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedMultiplicationServer) mustEmbedUnimplementedMultiplicationServer() {}
func (UnimplementedMultiplicationServer) testEmbeddedByValue()                        {}

// UnsafeMultiplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplicationServer will
// result in compilation errors.
type UnsafeMultiplicationServer interface {
	mustEmbedUnimplementedMultiplicationServer()
}

func RegisterMultiplicationServer(s grpc.ServiceRegistrar, srv MultiplicationServer) {
	// If the following call panics, it indicates UnimplementedMultiplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Multiplication_ServiceDesc, srv)
}

func _Multiplication_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplicationServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Multiplication_Multiply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplicationServer).Multiply(ctx, req.(*MultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Multiplication_ServiceDesc is the grpc.ServiceDesc for Multiplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Multiplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monax.example.multiplication.Multiplication",
	HandlerType: (*MultiplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiply",
			Handler:    _Multiplication_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiplication.proto",
}
