// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: runtime_parameters.proto

package proto

import (
	proto "github.com/openconfig/monax/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The service.spec.type field in the Kubernetes Service object.
// If unset, defaults to NodePort to support local 'kind' clusters that do not
// have a load balancer controller (like MetalLB).
type KubernetesHandlerParameters_ServiceType int32

const (
	KubernetesHandlerParameters_SERVICE_TYPE_UNSPECIFIED   KubernetesHandlerParameters_ServiceType = 0
	KubernetesHandlerParameters_SERVICE_TYPE_NODE_PORT     KubernetesHandlerParameters_ServiceType = 1
	KubernetesHandlerParameters_SERVICE_TYPE_LOAD_BALANCER KubernetesHandlerParameters_ServiceType = 2
)

// Enum value maps for KubernetesHandlerParameters_ServiceType.
var (
	KubernetesHandlerParameters_ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_NODE_PORT",
		2: "SERVICE_TYPE_LOAD_BALANCER",
	}
	KubernetesHandlerParameters_ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED":   0,
		"SERVICE_TYPE_NODE_PORT":     1,
		"SERVICE_TYPE_LOAD_BALANCER": 2,
	}
)

func (x KubernetesHandlerParameters_ServiceType) Enum() *KubernetesHandlerParameters_ServiceType {
	p := new(KubernetesHandlerParameters_ServiceType)
	*p = x
	return p
}

func (x KubernetesHandlerParameters_ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubernetesHandlerParameters_ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_parameters_proto_enumTypes[0].Descriptor()
}

func (KubernetesHandlerParameters_ServiceType) Type() protoreflect.EnumType {
	return &file_runtime_parameters_proto_enumTypes[0]
}

func (x KubernetesHandlerParameters_ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type KubernetesRuntimeParameters struct {
	state                  protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                      `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Kubernetes  *KubernetesHandlerParameters `protobuf:"bytes,2,opt,name=kubernetes"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KubernetesRuntimeParameters) Reset() {
	*x = KubernetesRuntimeParameters{}
	mi := &file_runtime_parameters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesRuntimeParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesRuntimeParameters) ProtoMessage() {}

func (x *KubernetesRuntimeParameters) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_parameters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubernetesRuntimeParameters) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *KubernetesRuntimeParameters) GetKubernetes() *KubernetesHandlerParameters {
	if x != nil {
		return x.xxx_hidden_Kubernetes
	}
	return nil
}

func (x *KubernetesRuntimeParameters) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *KubernetesRuntimeParameters) SetKubernetes(v *KubernetesHandlerParameters) {
	x.xxx_hidden_Kubernetes = v
}

func (x *KubernetesRuntimeParameters) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubernetesRuntimeParameters) HasKubernetes() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kubernetes != nil
}

func (x *KubernetesRuntimeParameters) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *KubernetesRuntimeParameters) ClearKubernetes() {
	x.xxx_hidden_Kubernetes = nil
}

type KubernetesRuntimeParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       *string
	Kubernetes *KubernetesHandlerParameters
}

func (b0 KubernetesRuntimeParameters_builder) Build() *KubernetesRuntimeParameters {
	m0 := &KubernetesRuntimeParameters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Kubernetes = b.Kubernetes
	return m0
}

type KubernetesHandlerParameters struct {
	state                             protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_KubeconfigPath         *string                                 `protobuf:"bytes,1,opt,name=kubeconfig_path,json=kubeconfigPath"`
	xxx_hidden_DockerHostUrl          *string                                 `protobuf:"bytes,2,opt,name=docker_host_url,json=dockerHostUrl,def=unix:///var/run/docker.sock"`
	xxx_hidden_DockerCertPath         *string                                 `protobuf:"bytes,3,opt,name=docker_cert_path,json=dockerCertPath"`
	xxx_hidden_ServiceType            KubernetesHandlerParameters_ServiceType `protobuf:"varint,4,opt,name=service_type,json=serviceType,enum=monax.kubernetes.KubernetesHandlerParameters_ServiceType,def=1"`
	xxx_hidden_ImageRepositoryAddress *string                                 `protobuf:"bytes,5,opt,name=image_repository_address,json=imageRepositoryAddress"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

// Default values for KubernetesHandlerParameters fields.
const (
	Default_KubernetesHandlerParameters_DockerHostUrl = string("unix:///var/run/docker.sock")
	Default_KubernetesHandlerParameters_ServiceType   = KubernetesHandlerParameters_SERVICE_TYPE_NODE_PORT
)

func (x *KubernetesHandlerParameters) Reset() {
	*x = KubernetesHandlerParameters{}
	mi := &file_runtime_parameters_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesHandlerParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesHandlerParameters) ProtoMessage() {}

func (x *KubernetesHandlerParameters) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_parameters_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubernetesHandlerParameters) GetKubeconfigPath() string {
	if x != nil {
		if x.xxx_hidden_KubeconfigPath != nil {
			return *x.xxx_hidden_KubeconfigPath
		}
		return ""
	}
	return ""
}

func (x *KubernetesHandlerParameters) GetDockerHostUrl() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if x.xxx_hidden_DockerHostUrl != nil {
				return *x.xxx_hidden_DockerHostUrl
			}
			return Default_KubernetesHandlerParameters_DockerHostUrl
		}
	}
	return Default_KubernetesHandlerParameters_DockerHostUrl
}

func (x *KubernetesHandlerParameters) GetDockerCertPath() string {
	if x != nil {
		if x.xxx_hidden_DockerCertPath != nil {
			return *x.xxx_hidden_DockerCertPath
		}
		return ""
	}
	return ""
}

func (x *KubernetesHandlerParameters) GetServiceType() KubernetesHandlerParameters_ServiceType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_ServiceType
		}
	}
	return Default_KubernetesHandlerParameters_ServiceType
}

func (x *KubernetesHandlerParameters) GetImageRepositoryAddress() string {
	if x != nil {
		if x.xxx_hidden_ImageRepositoryAddress != nil {
			return *x.xxx_hidden_ImageRepositoryAddress
		}
		return ""
	}
	return ""
}

func (x *KubernetesHandlerParameters) SetKubeconfigPath(v string) {
	x.xxx_hidden_KubeconfigPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *KubernetesHandlerParameters) SetDockerHostUrl(v string) {
	x.xxx_hidden_DockerHostUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *KubernetesHandlerParameters) SetDockerCertPath(v string) {
	x.xxx_hidden_DockerCertPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *KubernetesHandlerParameters) SetServiceType(v KubernetesHandlerParameters_ServiceType) {
	x.xxx_hidden_ServiceType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *KubernetesHandlerParameters) SetImageRepositoryAddress(v string) {
	x.xxx_hidden_ImageRepositoryAddress = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *KubernetesHandlerParameters) HasKubeconfigPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubernetesHandlerParameters) HasDockerHostUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KubernetesHandlerParameters) HasDockerCertPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *KubernetesHandlerParameters) HasServiceType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *KubernetesHandlerParameters) HasImageRepositoryAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *KubernetesHandlerParameters) ClearKubeconfigPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_KubeconfigPath = nil
}

func (x *KubernetesHandlerParameters) ClearDockerHostUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *KubernetesHandlerParameters) ClearDockerCertPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_DockerCertPath = nil
}

func (x *KubernetesHandlerParameters) ClearServiceType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

func (x *KubernetesHandlerParameters) ClearImageRepositoryAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ImageRepositoryAddress = nil
}

type KubernetesHandlerParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	KubeconfigPath *string
	// This is the default Linux value for reference.
	DockerHostUrl  *string
	DockerCertPath *string
	ServiceType    *KubernetesHandlerParameters_ServiceType
	// The address of the container registry to push images to (e.g.,
	// "docker.io/my-repo").
	// If set, the Docker image will be pushed to this address instead of being
	// loaded into a kind cluster.
	// However, if the image name already includes a repository address, this
	// field will be ignored.
	ImageRepositoryAddress *string
}

func (b0 KubernetesHandlerParameters_builder) Build() *KubernetesHandlerParameters {
	m0 := &KubernetesHandlerParameters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.KubeconfigPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_KubeconfigPath = b.KubeconfigPath
	}
	if b.DockerHostUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_DockerHostUrl = b.DockerHostUrl
	}
	if b.DockerCertPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_DockerCertPath = b.DockerCertPath
	}
	if b.ServiceType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_ServiceType = *b.ServiceType
	}
	if b.ImageRepositoryAddress != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ImageRepositoryAddress = b.ImageRepositoryAddress
	}
	return m0
}

type KubernetesComponentParameters struct {
	state                                  protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_DeploymentPath              *string                     `protobuf:"bytes,1,opt,name=deployment_path,json=deploymentPath"`
	xxx_hidden_ServicePath                 *string                     `protobuf:"bytes,2,opt,name=service_path,json=servicePath"`
	xxx_hidden_Docker                      *DockerBuildParameters      `protobuf:"bytes,3,opt,name=docker"`
	xxx_hidden_Vars                        map[string]string           `protobuf:"bytes,4,rep,name=vars" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_WaitForDeployment           bool                        `protobuf:"varint,5,opt,name=wait_for_deployment,json=waitForDeployment,def=1"`
	xxx_hidden_WaitForDeploymentTimeoutSec int64                       `protobuf:"varint,6,opt,name=wait_for_deployment_timeout_sec,json=waitForDeploymentTimeoutSec,def=600"`
	xxx_hidden_WaitForService              bool                        `protobuf:"varint,7,opt,name=wait_for_service,json=waitForService,def=1"`
	xxx_hidden_WaitForServiceTimeoutSec    int64                       `protobuf:"varint,8,opt,name=wait_for_service_timeout_sec,json=waitForServiceTimeoutSec,def=300"`
	xxx_hidden_InterfaceByPortName         map[string]*proto.Interface `protobuf:"bytes,9,rep,name=interface_by_port_name,json=interfaceByPortName" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData                 protoimpl.RaceDetectHookData
	XXX_presence                           [1]uint32
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

// Default values for KubernetesComponentParameters fields.
const (
	Default_KubernetesComponentParameters_WaitForDeployment           = bool(true)
	Default_KubernetesComponentParameters_WaitForDeploymentTimeoutSec = int64(600)
	Default_KubernetesComponentParameters_WaitForService              = bool(true)
	Default_KubernetesComponentParameters_WaitForServiceTimeoutSec    = int64(300)
)

func (x *KubernetesComponentParameters) Reset() {
	*x = KubernetesComponentParameters{}
	mi := &file_runtime_parameters_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesComponentParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesComponentParameters) ProtoMessage() {}

func (x *KubernetesComponentParameters) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_parameters_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubernetesComponentParameters) GetDeploymentPath() string {
	if x != nil {
		if x.xxx_hidden_DeploymentPath != nil {
			return *x.xxx_hidden_DeploymentPath
		}
		return ""
	}
	return ""
}

func (x *KubernetesComponentParameters) GetServicePath() string {
	if x != nil {
		if x.xxx_hidden_ServicePath != nil {
			return *x.xxx_hidden_ServicePath
		}
		return ""
	}
	return ""
}

func (x *KubernetesComponentParameters) GetDocker() *DockerBuildParameters {
	if x != nil {
		return x.xxx_hidden_Docker
	}
	return nil
}

func (x *KubernetesComponentParameters) GetVars() map[string]string {
	if x != nil {
		return x.xxx_hidden_Vars
	}
	return nil
}

func (x *KubernetesComponentParameters) GetWaitForDeployment() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_WaitForDeployment
		}
	}
	return Default_KubernetesComponentParameters_WaitForDeployment
}

func (x *KubernetesComponentParameters) GetWaitForDeploymentTimeoutSec() int64 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_WaitForDeploymentTimeoutSec
		}
	}
	return Default_KubernetesComponentParameters_WaitForDeploymentTimeoutSec
}

func (x *KubernetesComponentParameters) GetWaitForService() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			return x.xxx_hidden_WaitForService
		}
	}
	return Default_KubernetesComponentParameters_WaitForService
}

func (x *KubernetesComponentParameters) GetWaitForServiceTimeoutSec() int64 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 7) {
			return x.xxx_hidden_WaitForServiceTimeoutSec
		}
	}
	return Default_KubernetesComponentParameters_WaitForServiceTimeoutSec
}

func (x *KubernetesComponentParameters) GetInterfaceByPortName() map[string]*proto.Interface {
	if x != nil {
		return x.xxx_hidden_InterfaceByPortName
	}
	return nil
}

func (x *KubernetesComponentParameters) SetDeploymentPath(v string) {
	x.xxx_hidden_DeploymentPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *KubernetesComponentParameters) SetServicePath(v string) {
	x.xxx_hidden_ServicePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *KubernetesComponentParameters) SetDocker(v *DockerBuildParameters) {
	x.xxx_hidden_Docker = v
}

func (x *KubernetesComponentParameters) SetVars(v map[string]string) {
	x.xxx_hidden_Vars = v
}

func (x *KubernetesComponentParameters) SetWaitForDeployment(v bool) {
	x.xxx_hidden_WaitForDeployment = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *KubernetesComponentParameters) SetWaitForDeploymentTimeoutSec(v int64) {
	x.xxx_hidden_WaitForDeploymentTimeoutSec = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *KubernetesComponentParameters) SetWaitForService(v bool) {
	x.xxx_hidden_WaitForService = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *KubernetesComponentParameters) SetWaitForServiceTimeoutSec(v int64) {
	x.xxx_hidden_WaitForServiceTimeoutSec = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *KubernetesComponentParameters) SetInterfaceByPortName(v map[string]*proto.Interface) {
	x.xxx_hidden_InterfaceByPortName = v
}

func (x *KubernetesComponentParameters) HasDeploymentPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KubernetesComponentParameters) HasServicePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KubernetesComponentParameters) HasDocker() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Docker != nil
}

func (x *KubernetesComponentParameters) HasWaitForDeployment() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *KubernetesComponentParameters) HasWaitForDeploymentTimeoutSec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *KubernetesComponentParameters) HasWaitForService() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *KubernetesComponentParameters) HasWaitForServiceTimeoutSec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *KubernetesComponentParameters) ClearDeploymentPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DeploymentPath = nil
}

func (x *KubernetesComponentParameters) ClearServicePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ServicePath = nil
}

func (x *KubernetesComponentParameters) ClearDocker() {
	x.xxx_hidden_Docker = nil
}

func (x *KubernetesComponentParameters) ClearWaitForDeployment() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
}

func (x *KubernetesComponentParameters) ClearWaitForDeploymentTimeoutSec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
}

func (x *KubernetesComponentParameters) ClearWaitForService() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
}

func (x *KubernetesComponentParameters) ClearWaitForServiceTimeoutSec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
}

type KubernetesComponentParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentPath *string
	ServicePath    *string
	Docker         *DockerBuildParameters
	Vars           map[string]string
	// When true, wait for the replica count to be expected value. The replica
	// count represents the number of pods that should be in a healthy "running"
	// state.
	// Defaults to true if unset.
	WaitForDeployment *bool
	// The waiting timeout for the deployment to be in state "running" during
	// Start(). Only used if wait_for_deployment is true.
	// Defaults to 10 minutes if unset.
	WaitForDeploymentTimeoutSec *int64
	// When true, wait for the service to return an IP address during Start().
	// Defaults to true if unset.
	WaitForService *bool
	// Timeout for waiting for the service to return an IP address during Start.
	// Only used if wait_for_service is true.
	// Defaults to 5 minutes if unset.
	WaitForServiceTimeoutSec *int64
	InterfaceByPortName      map[string]*proto.Interface
}

func (b0 KubernetesComponentParameters_builder) Build() *KubernetesComponentParameters {
	m0 := &KubernetesComponentParameters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeploymentPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_DeploymentPath = b.DeploymentPath
	}
	if b.ServicePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_ServicePath = b.ServicePath
	}
	x.xxx_hidden_Docker = b.Docker
	x.xxx_hidden_Vars = b.Vars
	if b.WaitForDeployment != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_WaitForDeployment = *b.WaitForDeployment
	}
	if b.WaitForDeploymentTimeoutSec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_WaitForDeploymentTimeoutSec = *b.WaitForDeploymentTimeoutSec
	}
	if b.WaitForService != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_WaitForService = *b.WaitForService
	}
	if b.WaitForServiceTimeoutSec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_WaitForServiceTimeoutSec = *b.WaitForServiceTimeoutSec
	}
	x.xxx_hidden_InterfaceByPortName = b.InterfaceByPortName
	return m0
}

type DockerBuildParameters struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContextPath    *string                `protobuf:"bytes,1,opt,name=context_path,json=contextPath"`
	xxx_hidden_DockerfilePath *string                `protobuf:"bytes,2,opt,name=dockerfile_path,json=dockerfilePath,def=Dockerfile"`
	xxx_hidden_BuildImage     bool                   `protobuf:"varint,3,opt,name=build_image,json=buildImage"`
	xxx_hidden_LoadToKind     bool                   `protobuf:"varint,4,opt,name=load_to_kind,json=loadToKind"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for DockerBuildParameters fields.
const (
	Default_DockerBuildParameters_DockerfilePath = string("Dockerfile")
)

func (x *DockerBuildParameters) Reset() {
	*x = DockerBuildParameters{}
	mi := &file_runtime_parameters_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerBuildParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerBuildParameters) ProtoMessage() {}

func (x *DockerBuildParameters) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_parameters_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DockerBuildParameters) GetContextPath() string {
	if x != nil {
		if x.xxx_hidden_ContextPath != nil {
			return *x.xxx_hidden_ContextPath
		}
		return ""
	}
	return ""
}

func (x *DockerBuildParameters) GetDockerfilePath() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if x.xxx_hidden_DockerfilePath != nil {
				return *x.xxx_hidden_DockerfilePath
			}
			return Default_DockerBuildParameters_DockerfilePath
		}
	}
	return Default_DockerBuildParameters_DockerfilePath
}

func (x *DockerBuildParameters) GetBuildImage() bool {
	if x != nil {
		return x.xxx_hidden_BuildImage
	}
	return false
}

func (x *DockerBuildParameters) GetLoadToKind() bool {
	if x != nil {
		return x.xxx_hidden_LoadToKind
	}
	return false
}

func (x *DockerBuildParameters) SetContextPath(v string) {
	x.xxx_hidden_ContextPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DockerBuildParameters) SetDockerfilePath(v string) {
	x.xxx_hidden_DockerfilePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DockerBuildParameters) SetBuildImage(v bool) {
	x.xxx_hidden_BuildImage = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DockerBuildParameters) SetLoadToKind(v bool) {
	x.xxx_hidden_LoadToKind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DockerBuildParameters) HasContextPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DockerBuildParameters) HasDockerfilePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DockerBuildParameters) HasBuildImage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DockerBuildParameters) HasLoadToKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DockerBuildParameters) ClearContextPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContextPath = nil
}

func (x *DockerBuildParameters) ClearDockerfilePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *DockerBuildParameters) ClearBuildImage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_BuildImage = false
}

func (x *DockerBuildParameters) ClearLoadToKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LoadToKind = false
}

type DockerBuildParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The directory containing the service source code. Only files under this
	// directory can be used during the Docker build process.
	// Relative path from the Component txtpb file.
	ContextPath *string
	// The Dockerfile to use for the Docker build process.
	// Relative path from the context_path.
	DockerfilePath *string
	BuildImage     *bool
	LoadToKind     *bool
}

func (b0 DockerBuildParameters_builder) Build() *DockerBuildParameters {
	m0 := &DockerBuildParameters{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContextPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ContextPath = b.ContextPath
	}
	if b.DockerfilePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_DockerfilePath = b.DockerfilePath
	}
	if b.BuildImage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_BuildImage = *b.BuildImage
	}
	if b.LoadToKind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_LoadToKind = *b.LoadToKind
	}
	return m0
}

var File_runtime_parameters_proto protoreflect.FileDescriptor

const file_runtime_parameters_proto_rawDesc = "" +
	"\n" +
	"\x18runtime_parameters.proto\x12\x10monax.kubernetes\x1a!google/protobuf/go_features.proto\x1a\x11proto/monax.proto\"\x80\x01\n" +
	"\x1bKubernetesRuntimeParameters\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12M\n" +
	"\n" +
	"kubernetes\x18\x02 \x01(\v2-.monax.kubernetes.KubernetesHandlerParametersR\n" +
	"kubernetes\"\xce\x03\n" +
	"\x1bKubernetesHandlerParameters\x12'\n" +
	"\x0fkubeconfig_path\x18\x01 \x01(\tR\x0ekubeconfigPath\x12C\n" +
	"\x0fdocker_host_url\x18\x02 \x01(\t:\x1bunix:///var/run/docker.sockR\rdockerHostUrl\x12(\n" +
	"\x10docker_cert_path\x18\x03 \x01(\tR\x0edockerCertPath\x12t\n" +
	"\fservice_type\x18\x04 \x01(\x0e29.monax.kubernetes.KubernetesHandlerParameters.ServiceType:\x16SERVICE_TYPE_NODE_PORTR\vserviceType\x128\n" +
	"\x18image_repository_address\x18\x05 \x01(\tR\x16imageRepositoryAddress\"g\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVICE_TYPE_NODE_PORT\x10\x01\x12\x1e\n" +
	"\x1aSERVICE_TYPE_LOAD_BALANCER\x10\x02\"\x83\x06\n" +
	"\x1dKubernetesComponentParameters\x12'\n" +
	"\x0fdeployment_path\x18\x01 \x01(\tR\x0edeploymentPath\x12!\n" +
	"\fservice_path\x18\x02 \x01(\tR\vservicePath\x12?\n" +
	"\x06docker\x18\x03 \x01(\v2'.monax.kubernetes.DockerBuildParametersR\x06docker\x12M\n" +
	"\x04vars\x18\x04 \x03(\v29.monax.kubernetes.KubernetesComponentParameters.VarsEntryR\x04vars\x124\n" +
	"\x13wait_for_deployment\x18\x05 \x01(\b:\x04trueR\x11waitForDeployment\x12I\n" +
	"\x1fwait_for_deployment_timeout_sec\x18\x06 \x01(\x03:\x03600R\x1bwaitForDeploymentTimeoutSec\x12.\n" +
	"\x10wait_for_service\x18\a \x01(\b:\x04trueR\x0ewaitForService\x12C\n" +
	"\x1cwait_for_service_timeout_sec\x18\b \x01(\x03:\x03300R\x18waitForServiceTimeoutSec\x12}\n" +
	"\x16interface_by_port_name\x18\t \x03(\v2H.monax.kubernetes.KubernetesComponentParameters.InterfaceByPortNameEntryR\x13interfaceByPortName\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x18InterfaceByPortNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.monax.InterfaceR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x15DockerBuildParameters\x12!\n" +
	"\fcontext_path\x18\x01 \x01(\tR\vcontextPath\x123\n" +
	"\x0fdockerfile_path\x18\x02 \x01(\t:\n" +
	"DockerfileR\x0edockerfilePath\x12\x1f\n" +
	"\vbuild_image\x18\x03 \x01(\bR\n" +
	"buildImage\x12 \n" +
	"\fload_to_kind\x18\x04 \x01(\bR\n" +
	"loadToKindBEZ;github.com/openconfig/monax/runtime/kubernetesruntime/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_runtime_parameters_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runtime_parameters_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runtime_parameters_proto_goTypes = []any{
	(KubernetesHandlerParameters_ServiceType)(0), // 0: monax.kubernetes.KubernetesHandlerParameters.ServiceType
	(*KubernetesRuntimeParameters)(nil),          // 1: monax.kubernetes.KubernetesRuntimeParameters
	(*KubernetesHandlerParameters)(nil),          // 2: monax.kubernetes.KubernetesHandlerParameters
	(*KubernetesComponentParameters)(nil),        // 3: monax.kubernetes.KubernetesComponentParameters
	(*DockerBuildParameters)(nil),                // 4: monax.kubernetes.DockerBuildParameters
	nil,                                          // 5: monax.kubernetes.KubernetesComponentParameters.VarsEntry
	nil,                                          // 6: monax.kubernetes.KubernetesComponentParameters.InterfaceByPortNameEntry
	(*proto.Interface)(nil),                      // 7: monax.Interface
}
var file_runtime_parameters_proto_depIdxs = []int32{
	2, // 0: monax.kubernetes.KubernetesRuntimeParameters.kubernetes:type_name -> monax.kubernetes.KubernetesHandlerParameters
	0, // 1: monax.kubernetes.KubernetesHandlerParameters.service_type:type_name -> monax.kubernetes.KubernetesHandlerParameters.ServiceType
	4, // 2: monax.kubernetes.KubernetesComponentParameters.docker:type_name -> monax.kubernetes.DockerBuildParameters
	5, // 3: monax.kubernetes.KubernetesComponentParameters.vars:type_name -> monax.kubernetes.KubernetesComponentParameters.VarsEntry
	6, // 4: monax.kubernetes.KubernetesComponentParameters.interface_by_port_name:type_name -> monax.kubernetes.KubernetesComponentParameters.InterfaceByPortNameEntry
	7, // 5: monax.kubernetes.KubernetesComponentParameters.InterfaceByPortNameEntry.value:type_name -> monax.Interface
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_runtime_parameters_proto_init() }
func file_runtime_parameters_proto_init() {
	if File_runtime_parameters_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_parameters_proto_rawDesc), len(file_runtime_parameters_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_parameters_proto_goTypes,
		DependencyIndexes: file_runtime_parameters_proto_depIdxs,
		EnumInfos:         file_runtime_parameters_proto_enumTypes,
		MessageInfos:      file_runtime_parameters_proto_msgTypes,
	}.Build()
	File_runtime_parameters_proto = out.File
	file_runtime_parameters_proto_goTypes = nil
	file_runtime_parameters_proto_depIdxs = nil
}
