// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: monax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AbstractSut describes the top-level interface dependencies of a test.  These
// are the interfaces that the test will exercise directly in order to perform
// its validation.  Using the abstract SUT specification, Monax will create a
// SUT that consists of one or more components that satisfy the dependencies
// listed here.  If any of those components have dependencies of their own, the
// SUT will include any additional components necessary to also satisfy those
// transitive dependencies.  Only direct dependencies of the test should be
// listed here.
type AbstractSut struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequiredInterfaces *[]*Interface          `protobuf:"bytes,1,rep,name=required_interfaces,json=requiredInterfaces"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AbstractSut) Reset() {
	*x = AbstractSut{}
	mi := &file_monax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbstractSut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbstractSut) ProtoMessage() {}

func (x *AbstractSut) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AbstractSut) GetRequiredInterfaces() []*Interface {
	if x != nil {
		if x.xxx_hidden_RequiredInterfaces != nil {
			return *x.xxx_hidden_RequiredInterfaces
		}
	}
	return nil
}

func (x *AbstractSut) SetRequiredInterfaces(v []*Interface) {
	x.xxx_hidden_RequiredInterfaces = &v
}

type AbstractSut_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RequiredInterfaces []*Interface
}

func (b0 AbstractSut_builder) Build() *AbstractSut {
	m0 := &AbstractSut{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RequiredInterfaces = &b.RequiredInterfaces
	return m0
}

// Library describes the components available for inclusion in a SUT.  Monax may
// include any of these components in the SUT in order to satisfy direct and
// transitive dependencies.  The library must not contain duplicate
// implementations of interfaces, unsatisfied dependencies, or cyclic
// dependencies between components.
type Library struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Components *[]*Component          `protobuf:"bytes,1,rep,name=components"`
	xxx_hidden_Libraries  []string               `protobuf:"bytes,2,rep,name=libraries"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Library) Reset() {
	*x = Library{}
	mi := &file_monax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Library) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library) ProtoMessage() {}

func (x *Library) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Library) GetComponents() []*Component {
	if x != nil {
		if x.xxx_hidden_Components != nil {
			return *x.xxx_hidden_Components
		}
	}
	return nil
}

func (x *Library) GetLibraries() []string {
	if x != nil {
		return x.xxx_hidden_Libraries
	}
	return nil
}

func (x *Library) SetComponents(v []*Component) {
	x.xxx_hidden_Components = &v
}

func (x *Library) SetLibraries(v []string) {
	x.xxx_hidden_Libraries = v
}

type Library_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Components []*Component
	Libraries  []string
}

func (b0 Library_builder) Build() *Library {
	m0 := &Library{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Components = &b.Components
	x.xxx_hidden_Libraries = b.Libraries
	return m0
}

// Component describes an element available for inclusion in the SUT in order to
// satisfy direct or transitive dependencies.  A component may represent a
// single entity or an aggregation of entities.
type Component struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Kind               *string                `protobuf:"bytes,2,opt,name=kind"`
	xxx_hidden_ProvidedInterfaces *[]*Interface          `protobuf:"bytes,3,rep,name=provided_interfaces,json=providedInterfaces"`
	xxx_hidden_RequiredInterfaces *[]*Interface          `protobuf:"bytes,4,rep,name=required_interfaces,json=requiredInterfaces"`
	xxx_hidden_Parameters         *anypb.Any             `protobuf:"bytes,5,opt,name=parameters"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_monax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Component) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Component) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *Component) GetProvidedInterfaces() []*Interface {
	if x != nil {
		if x.xxx_hidden_ProvidedInterfaces != nil {
			return *x.xxx_hidden_ProvidedInterfaces
		}
	}
	return nil
}

func (x *Component) GetRequiredInterfaces() []*Interface {
	if x != nil {
		if x.xxx_hidden_RequiredInterfaces != nil {
			return *x.xxx_hidden_RequiredInterfaces
		}
	}
	return nil
}

func (x *Component) GetParameters() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *Component) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Component) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Component) SetProvidedInterfaces(v []*Interface) {
	x.xxx_hidden_ProvidedInterfaces = &v
}

func (x *Component) SetRequiredInterfaces(v []*Interface) {
	x.xxx_hidden_RequiredInterfaces = &v
}

func (x *Component) SetParameters(v *anypb.Any) {
	x.xxx_hidden_Parameters = v
}

func (x *Component) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Component) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Component) HasParameters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parameters != nil
}

func (x *Component) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Component) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Kind = nil
}

func (x *Component) ClearParameters() {
	x.xxx_hidden_Parameters = nil
}

type Component_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	Kind               *string
	ProvidedInterfaces []*Interface
	RequiredInterfaces []*Interface
	Parameters         *anypb.Any
}

func (b0 Component_builder) Build() *Component {
	m0 := &Component{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Kind = b.Kind
	}
	x.xxx_hidden_ProvidedInterfaces = &b.ProvidedInterfaces
	x.xxx_hidden_RequiredInterfaces = &b.RequiredInterfaces
	x.xxx_hidden_Parameters = b.Parameters
	return m0
}

// Interface describes a typed communication boundary between components.
type Interface struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Type        isInterface_Type       `protobuf_oneof:"type"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_monax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Interface) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Interface) GetDhcp() *Dhcp {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*interface_Dhcp); ok {
			return x.Dhcp
		}
	}
	return nil
}

func (x *Interface) GetGrpc() *Grpc {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*interface_Grpc); ok {
			return x.Grpc
		}
	}
	return nil
}

func (x *Interface) GetHttp() *Http {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*interface_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *Interface) GetHttps() *Https {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*interface_Https); ok {
			return x.Https
		}
	}
	return nil
}

func (x *Interface) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Interface) SetDhcp(v *Dhcp) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &interface_Dhcp{v}
}

func (x *Interface) SetGrpc(v *Grpc) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &interface_Grpc{v}
}

func (x *Interface) SetHttp(v *Http) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &interface_Http{v}
}

func (x *Interface) SetHttps(v *Https) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &interface_Https{v}
}

func (x *Interface) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Interface) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *Interface) HasDhcp() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*interface_Dhcp)
	return ok
}

func (x *Interface) HasGrpc() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*interface_Grpc)
	return ok
}

func (x *Interface) HasHttp() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*interface_Http)
	return ok
}

func (x *Interface) HasHttps() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*interface_Https)
	return ok
}

func (x *Interface) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Interface) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *Interface) ClearDhcp() {
	if _, ok := x.xxx_hidden_Type.(*interface_Dhcp); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Interface) ClearGrpc() {
	if _, ok := x.xxx_hidden_Type.(*interface_Grpc); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Interface) ClearHttp() {
	if _, ok := x.xxx_hidden_Type.(*interface_Http); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Interface) ClearHttps() {
	if _, ok := x.xxx_hidden_Type.(*interface_Https); ok {
		x.xxx_hidden_Type = nil
	}
}

const Interface_Type_not_set_case case_Interface_Type = 0
const Interface_Dhcp_case case_Interface_Type = 2
const Interface_Grpc_case case_Interface_Type = 3
const Interface_Http_case case_Interface_Type = 4
const Interface_Https_case case_Interface_Type = 5

func (x *Interface) WhichType() case_Interface_Type {
	if x == nil {
		return Interface_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *interface_Dhcp:
		return Interface_Dhcp_case
	case *interface_Grpc:
		return Interface_Grpc_case
	case *interface_Http:
		return Interface_Http_case
	case *interface_Https:
		return Interface_Https_case
	default:
		return Interface_Type_not_set_case
	}
}

type Interface_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name is a user supplied string to uniquely identify an interface within
	// a component.
	Name *string
	// Fields of oneof xxx_hidden_Type:
	Dhcp  *Dhcp
	Grpc  *Grpc
	Http  *Http
	Https *Https
	// -- end of xxx_hidden_Type
}

func (b0 Interface_builder) Build() *Interface {
	m0 := &Interface{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Dhcp != nil {
		x.xxx_hidden_Type = &interface_Dhcp{b.Dhcp}
	}
	if b.Grpc != nil {
		x.xxx_hidden_Type = &interface_Grpc{b.Grpc}
	}
	if b.Http != nil {
		x.xxx_hidden_Type = &interface_Http{b.Http}
	}
	if b.Https != nil {
		x.xxx_hidden_Type = &interface_Https{b.Https}
	}
	return m0
}

type case_Interface_Type protoreflect.FieldNumber

func (x case_Interface_Type) String() string {
	md := file_monax_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isInterface_Type interface {
	isInterface_Type()
}

type interface_Dhcp struct {
	Dhcp *Dhcp `protobuf:"bytes,2,opt,name=dhcp,oneof"`
}

type interface_Grpc struct {
	Grpc *Grpc `protobuf:"bytes,3,opt,name=grpc,oneof"`
}

type interface_Http struct {
	Http *Http `protobuf:"bytes,4,opt,name=http,oneof"`
}

type interface_Https struct {
	Https *Https `protobuf:"bytes,5,opt,name=https,oneof"`
}

func (*interface_Dhcp) isInterface_Type() {}

func (*interface_Grpc) isInterface_Type() {}

func (*interface_Http) isInterface_Type() {}

func (*interface_Https) isInterface_Type() {}

// Dhcp describes a DHCP interface.
type Dhcp struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=service_name,json=serviceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Dhcp) Reset() {
	*x = Dhcp{}
	mi := &file_monax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dhcp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dhcp) ProtoMessage() {}

func (x *Dhcp) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Dhcp) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *Dhcp) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Dhcp) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Dhcp) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type Dhcp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
}

func (b0 Dhcp_builder) Build() *Dhcp {
	m0 := &Dhcp{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

// Grpc describes a gRPC interface.
type Grpc struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=service_name,json=serviceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Grpc) Reset() {
	*x = Grpc{}
	mi := &file_monax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grpc) ProtoMessage() {}

func (x *Grpc) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Grpc) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *Grpc) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Grpc) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Grpc) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type Grpc_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
}

func (b0 Grpc_builder) Build() *Grpc {
	m0 := &Grpc{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

// Http describes an HTTP interface.
type Http struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=service_name,json=serviceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_monax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Http) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *Http) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Http) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Http) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type Http_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
}

func (b0 Http_builder) Build() *Http {
	m0 := &Http{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

// Https describes an HTTPS interface.
type Https struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,1,opt,name=service_name,json=serviceName"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Https) Reset() {
	*x = Https{}
	mi := &file_monax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Https) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Https) ProtoMessage() {}

func (x *Https) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Https) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *Https) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Https) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Https) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ServiceName = nil
}

type Https_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ServiceName *string
}

func (b0 Https_builder) Build() *Https {
	m0 := &Https{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	return m0
}

// RuntimeParameters describes the parameters used to configure the runtime.
type RuntimeParameters struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Parameters *anypb.Any             `protobuf:"bytes,1,opt,name=parameters"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RuntimeParameters) Reset() {
	*x = RuntimeParameters{}
	mi := &file_monax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeParameters) ProtoMessage() {}

func (x *RuntimeParameters) ProtoReflect() protoreflect.Message {
	mi := &file_monax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RuntimeParameters) GetParameters() *anypb.Any {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *RuntimeParameters) SetParameters(v *anypb.Any) {
	x.xxx_hidden_Parameters = v
}

func (x *RuntimeParameters) HasParameters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parameters != nil
}

func (x *RuntimeParameters) ClearParameters() {
	x.xxx_hidden_Parameters = nil
}

type RuntimeParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Parameters *anypb.Any
}

func (b0 RuntimeParameters_builder) Build() *RuntimeParameters {
	m0 := &RuntimeParameters{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Parameters = b.Parameters
	return m0
}

var File_monax_proto protoreflect.FileDescriptor

const file_monax_proto_rawDesc = "" +
	"\n" +
	"\vmonax.proto\x12\x05monax\x1a\x19google/protobuf/any.proto\x1a!google/protobuf/go_features.proto\"P\n" +
	"\vAbstractSut\x12A\n" +
	"\x13required_interfaces\x18\x01 \x03(\v2\x10.monax.InterfaceR\x12requiredInterfaces\"Y\n" +
	"\aLibrary\x120\n" +
	"\n" +
	"components\x18\x01 \x03(\v2\x10.monax.ComponentR\n" +
	"components\x12\x1c\n" +
	"\tlibraries\x18\x02 \x03(\tR\tlibraries\"\xeb\x01\n" +
	"\tComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12A\n" +
	"\x13provided_interfaces\x18\x03 \x03(\v2\x10.monax.InterfaceR\x12providedInterfaces\x12A\n" +
	"\x13required_interfaces\x18\x04 \x03(\v2\x10.monax.InterfaceR\x12requiredInterfaces\x124\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"parameters\"\xbc\x01\n" +
	"\tInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\x04dhcp\x18\x02 \x01(\v2\v.monax.DhcpH\x00R\x04dhcp\x12!\n" +
	"\x04grpc\x18\x03 \x01(\v2\v.monax.GrpcH\x00R\x04grpc\x12!\n" +
	"\x04http\x18\x04 \x01(\v2\v.monax.HttpH\x00R\x04http\x12$\n" +
	"\x05https\x18\x05 \x01(\v2\f.monax.HttpsH\x00R\x05httpsB\x06\n" +
	"\x04typeJ\x04\b\x06\x10\a\")\n" +
	"\x04Dhcp\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\")\n" +
	"\x04Grpc\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\")\n" +
	"\x04Http\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"*\n" +
	"\x05Https\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"I\n" +
	"\x11RuntimeParameters\x124\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"parametersB+Z!github.com/openconfig/monax/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_monax_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_monax_proto_goTypes = []any{
	(*AbstractSut)(nil),       // 0: monax.AbstractSut
	(*Library)(nil),           // 1: monax.Library
	(*Component)(nil),         // 2: monax.Component
	(*Interface)(nil),         // 3: monax.Interface
	(*Dhcp)(nil),              // 4: monax.Dhcp
	(*Grpc)(nil),              // 5: monax.Grpc
	(*Http)(nil),              // 6: monax.Http
	(*Https)(nil),             // 7: monax.Https
	(*RuntimeParameters)(nil), // 8: monax.RuntimeParameters
	(*anypb.Any)(nil),         // 9: google.protobuf.Any
}
var file_monax_proto_depIdxs = []int32{
	3,  // 0: monax.AbstractSut.required_interfaces:type_name -> monax.Interface
	2,  // 1: monax.Library.components:type_name -> monax.Component
	3,  // 2: monax.Component.provided_interfaces:type_name -> monax.Interface
	3,  // 3: monax.Component.required_interfaces:type_name -> monax.Interface
	9,  // 4: monax.Component.parameters:type_name -> google.protobuf.Any
	4,  // 5: monax.Interface.dhcp:type_name -> monax.Dhcp
	5,  // 6: monax.Interface.grpc:type_name -> monax.Grpc
	6,  // 7: monax.Interface.http:type_name -> monax.Http
	7,  // 8: monax.Interface.https:type_name -> monax.Https
	9,  // 9: monax.RuntimeParameters.parameters:type_name -> google.protobuf.Any
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_monax_proto_init() }
func file_monax_proto_init() {
	if File_monax_proto != nil {
		return
	}
	file_monax_proto_msgTypes[3].OneofWrappers = []any{
		(*interface_Dhcp)(nil),
		(*interface_Grpc)(nil),
		(*interface_Http)(nil),
		(*interface_Https)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monax_proto_rawDesc), len(file_monax_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monax_proto_goTypes,
		DependencyIndexes: file_monax_proto_depIdxs,
		MessageInfos:      file_monax_proto_msgTypes,
	}.Build()
	File_monax_proto = out.File
	file_monax_proto_goTypes = nil
	file_monax_proto_depIdxs = nil
}
